[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect - все маршруты направляются на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (опционально, если нужно избежать CORS)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.yandexcloud.net/api/:splat"
  status = 200
  force = true

# Заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Кэширование статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"